package com.smarthub.baseapplication.model.siteIBoard.newTowerCivilInfra

data class TwrCivilInfraTowerDetail(
    val AGId: Any,
    val AntennaSlot: Int,
    val Camouflage: Int,
    val Count: Int,
    val DesignedLoad: String,
    val EarthingCableLength: String,
    val EarthingCableType: Int,
    val FoundationSizeB: String,
    val FoundationSizeH: String,
    val FoundationSizeL: String,
    val FoundationType: List<Int>,
    val Height: String,
    val InstalledType: Int,
    val LightningArrester: Int,
    val LocationMark: String,
    val MakeType: Any,
    val MaterialUsed: Any,
    val OffsetPoleCount: Int,
    val OffsetPoleLength: String,
    val PitRodMaterial: Int,
    val Remark: String,
    val SizeB: String,
    val SizeH: String,
    val SizeL: String,
    val TowerPoleType: List<Int>,
    val Type: Int,
    val Weight: String,
    val created_at: String,
    val id: Int,
    val isActive: Boolean,
    val modified_at: String
)