package com.smarthub.baseapplication.model.siteInfo.siteAgreements

data class SiteacquisitionAgreement(
    var AgreementEffectiveDate: String,
    var AgreementExpiryDate: String,
    var AgreementPeriod: String,
    var AgreementType: String,
    val BookingCostCentre: String,
    val EBBillLimit: String,
    var EBBillingBasis: String,
    val EBInclusiveinRental: String,
    var EBPerUnitRate: String,
    var GroundUsableArea: String,
    val GroundacquiredArea: String,
    var InitialAnnualRentAmount: String,
    var LastRevisedRentAmount: String,
    var LastescalationDate: String,
    var LockInPeriod: String,
    var OnetimeAmount: String,
    val PODetails: List<PODetail>,
    var PeriodicRentPayableAmount: String,
    val PropertyAcquired: String,
    val PropertyOwnerPaymentDetails: List<PropertyOwnerPaymentDetail>,
    val PropertyOwnership: String,
    var RegistrationDate: String,
    val RegistrationNumber: String,
    var RentEscalation: String,
    var RentEscalationPeriod: String,
    val RentPaymentFrequency: String,
    var RentStartDate: String,
    val RooftopUsableArea: String,
    var RooftopacquiredArea: String,
    var SecurityDepositAmount: String,
    val created_at: String,
    val id: String,
    val isActive: String,
    val modified_at: String
)