package com.smarthub.baseapplication.model.siteInfo.siteAgreements

data class SiteacquisitionAgreement(
    val AgreementEffectiveDate: String,
    val AgreementExpiryDate: String,
    val AgreementPeriod: String,
    val AgreementType: String,
    val BookingCostCentre: String,
    val EBBillLimit: String,
    val EBBillingBasis: String,
    val EBInclusiveinRental: String,
    val EBPerUnitRate: String,
    val GroundUsableArea: String,
    val GroundacquiredArea: String,
    val InitialAnnualRentAmount: String,
    val LastRevisedRentAmount: String,
    val LastescalationDate: String,
    val LockInPeriod: String,
    val OnetimeAmount: String,
    val PODetails: List<PODetail>,
    val PeriodicRentPayableAmount: String,
    val PropertyAcquired: String,
    val PropertyOwnerPaymentDetails: List<PropertyOwnerPaymentDetail>,
    val PropertyOwnership: String,
    val RegistrationDate: String,
    val RegistrationNumber: String,
    val RentEscalation: String,
    val RentEscalationPeriod: String,
    val RentPaymentFrequency: String,
    val RentStartDate: String,
    val RooftopUsableArea: String,
    val RooftopacquiredArea: String,
    val SecurityDepositAmount: String,
    val created_at: String,
    val id: String,
    val isActive: String,
    val modified_at: String
)