package com.smarthub.baseapplication.model.taskModel

data class Processtemplatecallmanual(
    var AssigneeDepartment: String?=null,
    var Automaticescalationofoverdueitems: Boolean?=null,
    var FeatureName: String?=null,
    var NotificationSettingfornewaction: Boolean?=null,
    var PrerequisiteTask: String?=null,
    var Reminderofoutstandingactions: Boolean?=null,
    var NotificationSettingGeoTracking: Boolean?=null,
    var NotificationSettingGeoFencing: Boolean?=null,
    var SLA: Int?=null,
    var Taskid: Int?=null,
    var Taskinstruction: String?=null,
    var Distance: String?=null,
    var Taskname: String?=null,
    var Weightage: String?=null,
    var Where: List<String>?=null,
    var Workflow: String?=null,
    var actorname: String?=null,
    var documents: Boolean?=null,
    var enddate: String?=null,
    var geolevel: String?=null,
    var pictures: Boolean?=null,
    var priority: String?=null,
    var remark: String?=null,
    var role: String?=null,
    var siteid: String?=null,
    var sitename: String?=null,
    var startdate: String?=null
)