package com.smarthub.baseapplication.model.taskModel

data class TaskInfoItem(
    val AssigneeDepartment: String,
    val Auto: String,
    val Automaticescalationofoverdueitems: String,
    val FeatureName: String,
    val NotificationSettingfornewaction: String,
    val PrerequisiteTask: String,
    val Processname: String,
    val Projectname: String,
    val ReWorkflow: String,
    val Reminderofoutstandingactions: String,
    val SLA: String,
    val Sequenceid: String,
    val Status: String,
    val Taskinstruction: String,
    val Taskname: String,
    val Weightage: String,
    val Where: String,
    val Workflow: String,
    val actorname: String,
    val created_at: String,
    val documents: String,
    val enddate: String,
    val geolevel: String,
    val id: String,
    val isActive: String,
    val isCancel: String,
    val pictures: String,
    val reOpen: String,
    val siteid: String,
    val sitename: String,
    val startdate: String,
    val workorderid: String
)