package com.smarthub.baseapplication.utils;

public enum DropDowns {
    Sitestatus,
    Sitecategory,
    Sitetype,
    Siteownership,
    Buildingtype,
    Sitebillingstatus,
    Towncategory,
    RegistrationNumber,
    BookingCostCentre,
    RentPaymentFrequency,
    EBInclusiveinRental,
    EBBillLimit,
    PropertyOwnership,
    PropertyAcquired,
    AssignACQAcquisitionType,
    AssignACQAcquistionMode,
    AssignACQVendorName,
    BuildingBuildType,
    SiteAccessArea,
    GateAndFence,
    Potentialthreat,
    NoOfFloors,
    PropertyOfferforAcquisition,
    ASAcquisitionOfferType,
    ASRequiredAreaAvailable,
    ASOtherOperatorOnRoof,
    FiberLMCLaying,
    TowerPoleInstallation,
    EBsupplythroBuildingMeter,
    Equipementroom,
    RequiredAreaAvailable,
    OverallFeasibility,

}
