package com.smarthub.baseapplication.utils;

public enum DropDowns {
    Sitestatus,
    Sitecategory,
    Sitetype,
    Siteownership,
    Buildingtype,
    Sitebillingstatus,
    AcceptanceStatus,
    EquipmentName,
    Towncategory,
    CableName,
    RegistrationNumber,
    BookingCostCentre,
    RentPaymentFrequency,
    EBInclusiveinRental,
    EBBillLimit,
    PropertyOwnership,
    PropertyAcquired,
    AssignACQAcquisitionType,
    AssignACQAcquistionMode,
    AssignACQVendorName,
    BuildingBuildType,
    SiteAccessArea,
    GateAndFence,
    Potentialthreat,
    NoOfFloors,
    Acquisitiontype,
    PropertyOfferforAcquisition,
    ASAcquisitionOfferType,
    ASRequiredAreaAvailable,
    ASOtherOperatorOnRoof,
    FiberLMCLaying,
    TowerPoleInstallation,
    EBsupplythroBuildingMeter,
    Equipementroom,
    RequiredAreaAvailable,
    OverallFeasibility,
    PowerConnectionType,
    PaymentStatus,
    Climatezone,
    AcquisitionMode,
    Direction,
    LandType,
    SoilType,
    ExternalStructureType,

    ApplicationInitialCategory,
    ApplicationInitialApplicationType,
    ApplicationInitialApplicationStatus,
    AuthorityApplicationType,
    ApplicationInitialPreferredLaungauge,
    SRType,
    SRDetailRequesterCompany,
    SRDetailTechnology,
    Priority,
    SREquipmentsTechnology,
    SREquipmentsEquipment,
    SREquipmentsType,
    SRStatus,
    Technology,
    TowerPoleType,
    FoundationType,
    Costcentre,
//    Sitebillingstatus,
//    Towncategory,
    Sharingfeasibility,
    Locationzone,
    Projectname,
    Hubsite,
    Ldca,
    Scda,
    VendorCompany,
    // Site Info --> Geo Conditions Dropdowns
    Windzone,
    Seismiczone,
    Floodzone,
    Terraintype,
    // Site Info --> Safty Access Dropdowns
    Physicalsecurity,
    Videomonitoring,
    DangerSignage,
    CautionSignage,
    Siteaccess,
    // opco tenency --> Opco Info Dropdowns
    Opcositestatus,
    Opcositetype,
    Operatornetworktype,
    Alarmsextension,
    Rftechnology,
    Telecomequipmenttype,
    Rrucount,
    Sectorcount,
    Rackcount,
    Antenacount,
    Antenaslotused,
    InstallationVendor,
    MaintenanceVendor,
    Backhaultechnology,
    OpcoName,
    // opco tenency --> Rf Equipment Dropdowns
    OwnerCompany,
    OemCompany,
    OperationStatus,
    RackSpaceUsed,
    // opco tenency --> Backhaul Link Dropdowns
    BackhaulType,
    BackhaullinkType,
    BackhaulSiteCategory,
    // opco tenency --> Rf Anteena Dropdowns
    SpaceUsed,
    TowerPoleId,
    Sectornumber,
    AntenaShape,
    OperationalStatus,
    Loadtype,
    UserCompany,
    BackhaulAntenaTowerPoleId,
    RFSectornumber,
    BackhaulLinkUserCompany,
    BackhaulLinkOperationalStatus,
    BackhaulSpaceUsed,
    // plan design
    EquipmentType
}
