package com.smarthub.baseapplication.model.serviceRequest

data class SRDetails(
    var Area: String,
    var Circle: String,
    var CityOrTown: String,
    var ExpectedDate: String,
    var HubSite: Int,
    var OpcoName: String,
    var OpcoSiteName: String,
    var OpcoSiteType: String,
    var Pincode: String,
    var Priority: List<Int>,
    var RequestDate: String,
    var RequesterCompany: String,
    var SRStatus: List<Int>,
    var OpcoCompany: List<Int>,
    var SRType: Int,
    var SiteTypeCode: List<Int>,
    var SiteClass: List<Int>,
    var Opcositetype: List<Int>,
    var Technology: List<Int>,
    var SearchRadius: String,
    var created_at: String,
    var id: Int,
    var SectorCount: Int,
    var isActive: Boolean,
    var locLatitude: String,
    var locLongitude: String,
    var modified_at: String
)