package com.smarthub.baseapplication.model.siteInfo

data class Opcoinfo(
    val Alarmsextension: List<Alarmsextension>,
    val Antenacount: List<Antenacount>,
    val Antenaslotused: List<Antenaslotused>,
    val Backhaultechnology: List<Backhaultechnology>,
    val InstallationVendor: List<InstallationVendor>,
    val MaintenanceVendor: List<MaintenanceVendor>,
    val OpcoName: List<Any>,
    val OpcoSiteID: String,
    val OpcoSiteName: String,
    val Opcosignoffdate: String,
    val Opcositestatus: List<Opcositestatu>,
    val Opcositetype: List<Opcositetype>,
    val Operatormaintenancelocation: String,
    val Operatornetworktype: List<Operatornetworktype>,
    val Rackcount: List<Rackcount>,
    val Rftechnology: List<Rftechnology>,
    val Rrucount: List<Rrucount>,
    val Sectorcount: List<Sectorcount>,
    val Siteinchargeemail: String,
    val Siteinchargename: String,
    val Siteinchargenumber: String,
    val Telecomequipmenttype: List<Telecomequipmenttype>,
    val committedNWA: String,
    val created_at: String,
    val id: Int,
    val isActive: Boolean,
    val modified_at: String,
    val opcofilesattachments: Any,
    val rfiAcceptanceDate: String,
    val rfrDate: String
)