package com.smarthub.baseapplication.model.siteInfo.opcoInfo

data class Opcoinfo(
    var Alarmsextension: String,
    var Antenacount: String,
    var Antenaslotused: String,
    var Backhaultechnology: String,
    var InstallationVendor: String,
    var MaintenanceVendor: String,
    var Operatornetworktype: String,
    var OpcoName: String,
    var OpcoSiteID: String,
    var OpcoSiteName: String,
    var Opcosignoffdate: String,
    var Opcositestatus: String,
    var Opcositetype: String,
    var Operatormaintenancelocation: String,

    var Rackcount: String,
    var Rftechnology: String,
    var Rrucount: String,
    var Sectorcount: String,
    var Siteinchargeemail: String,
    var Siteinchargename: String,
    var Siteinchargenumber: String,
    var Telecomequipmenttype: String,
    var committedNWA: String,
    var created_at: String,
    var id: Int,
    var isActive: Boolean,
    var modified_at: String,
    var opcofilesattachments: Any,
    var rfiAcceptanceDate: String,
    var rfrDate: String
)