package com.smarthub.baseapplication.model.siteInfo.opcoInfo

data class RfAnteenaData(
    val AntenaMake: String,
    val AntenaModel: String,
    val AntenaOrentiation: String,
    val AntenaSerialNumber: String,
    val AntenaShape: String,
    val AntenaSize: String,
    val AntenaTilt: String,
    val AntenaTotalPowerRating: String,
    val AntenaType: String,
    val AntenaWeight: String,
    val AntenaSizeL:String,
    val AntenaSizeB:String,
    val AntenaSizeH:String,
    val CPRICableLength: String,
    val FeederCableLength: String,
    val GPSCableLength: String,
    val InstallationDate: String,
    val InstalledHeight: String,
    val LinkOperationalStatus: String,
    val OwnerCompany: String,
    val PowerCableLength: String,
    val Remarks: String,
    val SectorNumber: String,
    val SpaceUsed: String,
    val Technology: String,
    val TowerPoleId: String,
    val UserCompany: String,
    val created_at: String,
    val id: String,
    val isActive: String,
    val modified_at: String,
    val ConsumableMaterial: List<Any>,

)