package com.smarthub.baseapplication.model.siteInfo.opcoInfo

data class RfAnteenaData(
    var AntenaMake: String,
    var AntenaModel: String,
    var AntenaOrentiation: String,
    var AntenaSerialNumber: String,
    var AntenaShape: String,
    var AntenaSize: String,
    var AntenaTilt: String,
    var AntenaTotalPowerRating: String,
    var AntenaType: String,
    var AntenaWeight: String,
    var AntenaSizeL:String,
    var AntenaSizeB:String,
    var AntenaSizeH:String,
    var CPRICableLength: String,
    var FeederCableLength: String,
    var GPSCableLength: String,
    var InstallationDate: String,
    var InstalledHeight: String,
    var LinkOperationalStatus: String,
    var OwnerCompany: String,
    var PowerCableLength: String,
    var Remarks: String,
    var SectorNumber: String,
    var SpaceUsed: String,
    var Technology: String,
    var TowerPoleId: String,
    var UserCompany: String,
    var created_at: String,
    var id: String,
    var isActive: String,
    var modified_at: String,
    var ConsumableMaterial: List<Any>,

    )